### ISSUE TITLE
Bug when predicting with a single observation

### ISSUE THREAD

**Issue by maksymiuks** [mlr3learners/mlr3learners.gbm#4]
Hi again,

I've found another bug when trying to predict one observation. The code is below
```
library(mlr3)
library(mlr3learners)
library(mlr3learners.gbm)
library(DALEXtra)

HR_task <- TaskClassif$new(id = "HR", backend = HR, target = "status")
HR_gbm <- lrn("classif.gbm", predict_type = "prob")
HR_gbm$param_set$values <- list(n.trees = 500, distribution = "multinomial")
HR_gbm$train(HR_task)
HR_gbm$predict_newdata(HR[1,])

HR_ranger <- lrn("classif.ranger", predict_type = "prob")
HR_ranger$train(HR_task)
HR_ranger$predict_newdata(HR[1,])
```

as an example of proper evaluation ranger code is at the bottom of the chunk.

Best

Szymon

**Comment by pat-s** [comment]
@be-marc Could you take a look?

**Comment by be-marc** [comment]
Fixed. Thanks for reporting this. 

@pat-s You already fixed this in mlr 7 months ago. I used your code.

**Comment by pat-s** [comment]
Thanks. Please fix the lintr and do a drat patch release :)
